{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-coloc
  version: '4.0.4'

source:
  git_url: https://github.com/chr1swallace/coloc
  git_tag: 2652098dcc47f9a620731022db7d86b27296137c

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, testthat, bindata, mvtnorm, magrittr, rmarkdown
requirements:
  build:
    - {{posix}}filesystem        # [win]
    - {{posix}}git
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-bma
    - r-data.table
    - r-ggplot2
    - bioconductor-snpstats
    - r-viridis

  run:
    - r-base
    - r-bma
    - r-data.table
    - r-ggplot2
    - bioconductor-snpstats
    - r-viridis

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('coloc')"           # [not win]
    - "\"%R%\" -e \"library('coloc')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/chr1swallace/coloc

  license: GPL-3
  summary: Performs the colocalisation tests described in Plagnol et al (2009) <doi:10.1093/biostatistics/kxn039>,
    Wallace et al (2013) <doi:10.1002/gepi.21765>, Giambartolomei et al (2013) <doi:10.1371/journal.pgen.1004383>,
    Wallace (2020) <doi:doi.org/10.1371/journal.pgen.1008720>.

  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

# The original CRAN metadata for this package was:

# Package: coloc
# Type: Package
# Imports: data.table, ggplot2, snpStats, BMA, methods, viridis, stats, grDevices, utils
# Suggests: knitr, testthat, bindata, mvtnorm, magrittr, rmarkdown
# biocViews:
# Title: Colocalisation Tests of Two Genetic Traits
# Version: 4.0-4
# Date: 2020-05-02
# Authors@R: c(person("Chris", "Wallace", role=c("aut","cre"), email = "cew54@cam.ac.uk"), person("Claudia","Giambartolomei", role="aut", email="claudia.giambartolomei.10@ucl.ac.uk"), person("Vincent","Plagnol", role="ctb", email="v.plagnol@ucl.ac.uk"))
# Maintainer: Chris Wallace <cew54@cam.ac.uk>
# Description: Performs the colocalisation tests described in Plagnol et al (2009) <doi:10.1093/biostatistics/kxn039>, Wallace et al (2013) <doi:10.1002/gepi.21765>, Giambartolomei et al (2013) <doi:10.1371/journal.pgen.1004383>, Wallace (2020) <doi:doi.org/10.1371/journal.pgen.1008720>.
# License: GPL
# LazyLoad: yes
# VignetteBuilder: knitr
# Roxygen: list(markdown = TRUE)
# RoxygenNote: 7.1.0
# Encoding: UTF-8
# URL: https://github.com/chr1swallace/coloc
# BugReports: https://github.com/chr1swallace/coloc/issues

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
