{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-susier
  version: '0.11.43.dev1'

source:
  git_url: https://github.com/stephenslab/susieR
  git_tag: 58073151c3262c06e543f6eae8d181cd4a3639ac

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}filesystem        # [win]
    - {{posix}}git
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-matrix
    - r-expm
    - r-matrixstats
    - r-mixsqp
    - r-reshape
    - r-ggplot2

  run:
    - r-base
    - r-matrix
    - r-expm
    - r-matrixstats
    - r-mixsqp
    - r-reshape
    - r-ggplot2

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('susieR')"           # [not win]
    - "\"%R%\" -e \"library('susieR')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/stephenslab/susieR
  license: MIT
  summary: Implements methods for variable selection in linear
    regression based on the "Sum of Single Effects" (SuSiE) model, as
    described in Wang et al (2020) <DOI:10.1101/501114>. These methods
    provide simple summaries, called "Credible Sets", for accurately
    quantifying uncertainty in which variables should be selected.
    The methods are motivated by genetic fine-mapping applications,
    and are particularly well-suited to settings where variables are
    highly correlated and detectable effects are sparse. The fitting
    algorithm, a Bayesian analogue of stepwise selection methods
    called "Iterative Bayesian Stepwise Selection" (IBSS), is simple
    and fast, allowing the SuSiE model be fit to large data sets
    (thousands of samples and hundreds of thousands of variables).
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE
