{% set version = '5.4.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mclust
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mclust_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mclust/mclust_{{ version }}.tar.gz
  sha256: e69e80786ee71e856fe0b7f7741b0a49503d8433ee92d8f3417ec49f20f3a5a3

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr (>= 1.12), rmarkdown (>= 0.9), mix (>= 1.0), geometry (>= 0.3-6), MASS
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('mclust')"           # [not win]
    - "\"%R%\" -e \"library('mclust')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.stat.washington.edu/mclust/
  license: GPL (>= 2)
  summary: Gaussian finite mixture models fitted via EM algorithm for model-based clustering,
    classification, and density estimation, including Bayesian regularization, dimension
    reduction for visualisation, and resampling-based inference.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

# The original CRAN metadata for this package was:

# Package: mclust
# Version: 5.4.3
# Date: 2019-03-14
# Title: Gaussian Mixture Modelling for Model-Based Clustering, Classification, and Density Estimation
# Description: Gaussian finite mixture models fitted via EM algorithm for model-based clustering, classification, and density estimation, including Bayesian regularization, dimension reduction for visualisation, and resampling-based inference.
# Authors@R: c(person("Chris", "Fraley", role = "aut"), person("Adrian E.", "Raftery", role = "aut", comment = c(ORCID = "0000-0002-6589-301X")), person("Luca", "Scrucca", role = c("aut", "cre"), email = "luca.scrucca@unipg.it", comment = c(ORCID = "0000-0003-3826-0484")), person("Thomas Brendan", "Murphy", role = "ctb", comment = c(ORCID = "0000-0002-5668-7046")), person("Michael", "Fop", role = "ctb", comment = c(ORCID = "0000-0003-3936-2757")))
# Depends: R (>= 3.0)
# Imports: stats, utils, graphics, grDevices
# Suggests: knitr (>= 1.12), rmarkdown (>= 0.9), mix (>= 1.0), geometry (>= 0.3-6), MASS
# License: GPL (>= 2)
# URL: http://www.stat.washington.edu/mclust/
# VignetteBuilder: knitr
# Repository: CRAN
# ByteCompile: true
# LazyData: yes
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-03-14 12:17:38 UTC; luca
# Author: Chris Fraley [aut], Adrian E. Raftery [aut] (<https://orcid.org/0000-0002-6589-301X>), Luca Scrucca [aut, cre] (<https://orcid.org/0000-0003-3826-0484>), Thomas Brendan Murphy [ctb] (<https://orcid.org/0000-0002-5668-7046>), Michael Fop [ctb] (<https://orcid.org/0000-0003-3936-2757>)
# Maintainer: Luca Scrucca <luca.scrucca@unipg.it>
# Date/Publication: 2019-03-14 14:10:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
