package:
  name: mpebpm
  version: '0.2.dev2'

build:
  number: 0

source:
  git_url: https://github.com/aksarkar/mpebpm
  git_tag: 6b7df3f6ab5b56b7090ca90c080f0cd7a187b065

requirements:
  build:
    - future
    - numpy >=1.18
    - python {{PY_VER}}*,>=3.6.9
    - pytorch
    - scipy

  test:
    requires:
      - pytest

  run:
    - future
    - numpy >=1.18
    - python {{PY_VER}}*,>=3.6.9
    - scipy
    - pytorch

about:
  home: https://www.github.com/aksarkar/mpebpm
  license: MIT
  summary:
    'This package provides GPU-accelerated inference for the Empirical Bayes
    Poisson Means (EBPM) problem. This model can be used to model variation in
    scRNA-seq data due to measurement error, as well as variation in true gene
    expression values (Sarkar and Stephens 2020).

    This implementation readily supports fitting the model for data on the
    order of 10⁶ cells and 10⁴ genes in parallel. It also supports fitting
    multiple EBPM problems per gene in parallel, as arise when e.g., cells have
    been assigned to groups (clusters). For example, we have used the method to
    solve 537,678 EBPM problems (54 conditions by 9,957 genes) in parallel in a
    few minutes (Sarkar et al. 2019).'
