{% set version = '2.5-16' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-varbvs
  version: {{ version|replace("-", ".") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/varbvs_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/varbvs/varbvs_{{ version }}.tar.gz
  sha256: 0df51136bded6249f2ad158e4f5efcf67fed60bfdf60608f0f00c675f13e515e

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: curl, glmnet, qtl, knitr, rmarkdown, testthat
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-matrix
    - r-rcpp
    - r-lattice
    - r-latticeextra
    - r-nor1mix

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-matrix
    - r-rcpp
    - r-lattice
    - r-latticeextra
    - r-nor1mix

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('varbvs')"           # [not win]
    - "\"%R%\" -e \"library('varbvs')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://github.com/pcarbo/varbvs
  license: GPL (>= 3)
  summary: Fast algorithms for fitting Bayesian variable selection models and computing Bayes
    factors, in which the outcome (or response variable) is modeled using a linear regression
    or a logistic regression. The algorithms are based on the variational approximations
    described in "Scalable variational inference for Bayesian variable selection in
    regression, and its accuracy in genetic association studies" (P. Carbonetto & M.
    Stephens, 2012, <DOI:10.1214/12-BA703>). This software has been applied to large
    data sets with over a million variables and thousands of samples.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

# The original CRAN metadata for this package was:

# Package: varbvs
# Encoding: UTF-8
# Type: Package
# Version: 2.5-16
# Date: 2019-03-07
# Title: Large-Scale Bayesian Variable Selection Using Variational Methods
# Authors@R: c(person("Peter","Carbonetto",role=c("aut","cre"), email="peter.carbonetto@gmail.com"), person("Matthew","Stephens",role="aut"), person("David","Gerard",role="ctb"))
# Maintainer: Peter Carbonetto <peter.carbonetto@gmail.com>
# Description: Fast algorithms for fitting Bayesian variable selection models and computing Bayes factors, in which the outcome (or response variable) is modeled using a linear regression or a logistic regression. The algorithms are based on the variational approximations described in "Scalable variational inference for Bayesian variable selection in regression, and its accuracy in genetic association studies" (P. Carbonetto & M. Stephens, 2012, <DOI:10.1214/12-BA703>). This software has been applied to large data sets with over a million variables and thousands of samples.
# Depends: R (>= 3.1.0)
# Imports: methods, Matrix, stats, graphics, lattice, latticeExtra, Rcpp, nor1mix
# Suggests: curl, glmnet, qtl, knitr, rmarkdown, testthat
# License: GPL (>= 3)
# NeedsCompilation: yes
# LazyData: true
# URL: http://github.com/pcarbo/varbvs
# BugReports: http://github.com/pcarbo/varbvs/issues
# LinkingTo: Rcpp
# VignetteBuilder: knitr
# Packaged: 2019-03-07 20:31:05 UTC; pcarbo
# Author: Peter Carbonetto [aut, cre], Matthew Stephens [aut], David Gerard [ctb]
# Repository: CRAN
# Date/Publication: 2019-03-07 21:10:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
