{% set version = '2.2-32' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ashr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ashr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ashr/ashr_{{ version }}.tar.gz
  sha256: 640b5720cc802d35a8d62af38f2d922437426ab7035bc848d2c3dff00481734c

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr, rmarkdown, ggplot2, REBayes
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-matrix
    - r-rcpp >=0.10.5
    - r-squarem
    - r-assertthat
    - r-doparallel
    - r-etrunct
    - r-foreach
    - r-mixsqp
    - r-pscl
    - r-truncnorm

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-matrix
    - r-rcpp >=0.10.5
    - r-squarem
    - r-assertthat
    - r-doparallel
    - r-etrunct
    - r-foreach
    - r-mixsqp
    - r-pscl
    - r-truncnorm

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('ashr')"           # [not win]
    - "\"%R%\" -e \"library('ashr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/stephens999/ashr
  license: GPL (>= 3)
  summary: 'The R package ''ashr'' implements an Empirical Bayes approach for large-scale hypothesis
    testing and false discovery rate (FDR) estimation based on the methods proposed
    in M. Stephens, 2016, "False discovery rates: a new deal", <DOI:10.1093/biostatistics/kxw041>.
    These methods can be applied whenever two sets of summary statistics---estimated
    effects and standard errors---are available, just as ''qvalue'' can be applied to
    previously computed p-values. Two main interfaces are provided: ash(), which is
    more user-friendly; and ash.workhorse(), which has more options and is geared toward
    advanced users. The ash() and ash.workhorse() also provides a flexible modeling
    interface that can accomodate a variety of likelihoods (e.g., normal, Poisson) and
    mixture priors (e.g., uniform, normal).'

  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

# The original CRAN metadata for this package was:

# Package: ashr
# Encoding: UTF-8
# Type: Package
# Maintainer: Peter Carbonetto <pcarbo@uchicago.edu>
# Authors@R: c(person("Matthew","Stephens",role="aut", email="mstephens@uchicago.edu"), person("Peter","Carbonetto",role=c("aut","cre"), email="pcarbo@uchicago.edu"), person("Chaoxing","Dai",role="ctb"), person("David","Gerard",role="aut"), person("Mengyin","Lu",role="aut"), person("Lei","Sun",role="aut"), person("Jason","Willwerscheid",role="aut"), person("Nan","Xiao",role="aut"), person("Mazon","Zeng",role="ctb"))
# Version: 2.2-32
# Date: 2019-02-18
# Title: Methods for Adaptive Shrinkage, using Empirical Bayes
# Description: The R package 'ashr' implements an Empirical Bayes approach for large-scale hypothesis testing and false discovery rate (FDR) estimation based on the methods proposed in M. Stephens, 2016, "False discovery rates: a new deal", <DOI:10.1093/biostatistics/kxw041>. These methods can be applied whenever two sets of summary statistics---estimated effects and standard errors---are available, just as 'qvalue' can be applied to previously computed p-values. Two main interfaces are provided: ash(), which is more user-friendly; and ash.workhorse(), which has more options and is geared toward advanced users. The ash() and ash.workhorse() also provides a flexible modeling interface that can accomodate a variety of likelihoods (e.g., normal, Poisson) and mixture priors (e.g., uniform, normal).
# Depends: R (>= 3.1.0)
# Imports: Matrix, stats, graphics, assertthat, truncnorm, mixsqp, SQUAREM, doParallel, pscl, Rcpp (>= 0.10.5), foreach, etrunct
# LinkingTo: Rcpp
# Suggests: testthat, knitr, rmarkdown, ggplot2, REBayes
# License: GPL (>= 3)
# NeedsCompilation: yes
# LazyData: true
# URL: https://github.com/stephens999/ashr
# BugReports: https://github.com/stephens999/ashr/issues
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# Packaged: 2019-02-21 15:46:47 UTC; pcarbo
# Author: Matthew Stephens [aut], Peter Carbonetto [aut, cre], Chaoxing Dai [ctb], David Gerard [aut], Mengyin Lu [aut], Lei Sun [aut], Jason Willwerscheid [aut], Nan Xiao [aut], Mazon Zeng [ctb]
# Repository: CRAN
# Date/Publication: 2019-02-22 09:50:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
