{% set name = "pyplink" %}
{% set version = "1.3.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 5de7f0100e2dbaa0e0562cdd3352d63810449f27c11e286d1eafbccd3636098b

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy >=1.8.2
    - pandas >=0.17.1
    - pip
    - python
    - six >=1.9.0
  run:
    - numpy >=1.8.2
    - pandas >=0.17.1
    - python
    - six >=1.9.0

test:
  imports:
    - pyplink
    - pyplink.tests

about:
  home: "https://github.com/lemieuxl/pyplink"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Python module to read binary Plink files."
  doc_url: "https://lemieuxl.github.io/pyplink/index.html"
  dev_url: 

extra:
  recipe-maintainers:
    - aksarkar
