{% set version = '1.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-grove
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/grove_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/grove/grove_{{ version }}.tar.gz
  sha256: bdac7690a1b2b5b50b24be332379037d6c04e9ebd36d386c64c7dfd35b911a3b

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-rcpp >=0.11.2
    - r-rcpparmadillo
    - r-wavethresh

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.11.2
    - r-rcpparmadillo
    - r-wavethresh

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('grove')"           # [not win]
    - "\"%R%\" -e \"library('grove')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=grove
  license: GPL-3
  summary: 'Functional denoising and functional ANOVA through wavelet-domain Markov groves. Fore
    more details see: Ma L. and Soriano J. (2016) Efficient functional ANOVA through
    wavelet-domain Markov groves. <arXiv:1602.03990v2 [stat.ME]>.'

  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

# The original CRAN metadata for this package was:

# Package: grove
# Type: Package
# Title: Wavelet Functional ANOVA Through Markov Groves
# Version: 1.1
# Date: 2018-01-07
# Author: Jacopo Soriano and Li Ma
# Maintainer: Jacopo Soriano <jsoriano.stat@gmail.com>
# Description: Functional denoising and functional ANOVA through wavelet-domain Markov groves. Fore more details see: Ma L. and Soriano J. (2016) Efficient functional ANOVA through wavelet-domain Markov groves. <arXiv:1602.03990v2 [stat.ME]>.
# License: GPL (>= 3)
# Imports: methods, Rcpp (>= 0.11.2), wavethresh
# LinkingTo: Rcpp, RcppArmadillo
# NeedsCompilation: yes
# Packaged: 2018-01-07 23:19:22 UTC; uganaga
# Repository: CRAN
# Date/Publication: 2018-01-07 23:37:09 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
