{% set version = '0.2.50' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mashr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mashr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mashr/mashr_{{ version }}.tar.gz
  sha256: 2f35f86a90b8b6e3f4f438a9af84a825a4615d6f6a6766959e66783ddd814536

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: MASS, REBayes, corrplot, testthat, kableExtra, knitr, rmarkdown, profmem, flashr (>= 0.6.7)
requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-rcpp >=0.12.11
    - r-rcpparmadillo
    - r-rcppgsl >=0.3.8
    - r-abind
    - r-ashr >=2.2_22
    - r-assertthat
    - r-mvtnorm
    - r-plyr
    - r-rmeta
    - r-softimpute

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.12.11
    - r-rcpparmadillo
    - r-rcppgsl >=0.3.8
    - r-abind
    - r-ashr >=2.2_22
    - r-assertthat
    - r-mvtnorm
    - r-plyr
    - r-rmeta
    - r-softimpute

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('mashr')"           # [not win]
    - "\"%R%\" -e \"library('mashr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/stephenslab/mashr

  license: BSD_3_clause
  summary: Implements the multivariate adaptive shrinkage (mash) method of Urbut et al (2019)
    <DOI:10.1038/s41588-018-0268-8> for estimating and testing large numbers of effects
    in many conditions (or many outcomes). Mash takes an empirical Bayes approach to
    testing and effect estimation; it estimates patterns of similarity among conditions,
    then exploits these patterns to improve accuracy of the effect estimates. The core
    linear algebra is implemented in C++ for fast model fitting and posterior computation.

  license_family: BSD
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause'
    - LICENSE

# The original CRAN metadata for this package was:

# Package: mashr
# Type: Package
# Encoding: UTF-8
# Title: Multivariate Adaptive Shrinkage
# Version: 0.2.50
# Date: 2021-05-19
# Authors@R: c(person("Matthew","Stephens",role="aut"), person("Sarah","Urbut",role="aut"), person("Gao","Wang",role="aut"), person("Yuxin","Zou",role="aut"), person("Yunqi","Yang",role="ctb"), person("Sam","Roweis",role="cph"), person("David","Hogg",role="cph"), person("Jo","Bovy",role="cph"), person("Peter","Carbonetto",role=c("aut","cre"), email="peter.carbonetto@gmail.com"))
# Description: Implements the multivariate adaptive shrinkage (mash) method of Urbut et al (2019) <DOI:10.1038/s41588-018-0268-8> for estimating and testing large numbers of effects in many conditions (or many outcomes). Mash takes an empirical Bayes approach to testing and effect estimation; it estimates patterns of similarity among conditions, then exploits these patterns to improve accuracy of the effect estimates. The core linear algebra is implemented in C++ for fast model fitting and posterior computation.
# URL: https://github.com/stephenslab/mashr
# BugReports: https://github.com/stephenslab/mashr/issues
# License: BSD_3_clause + file LICENSE
# Copyright: file COPYRIGHTS
# SystemRequirements: C++11
# Depends: R (>= 3.3.0), ashr (>= 2.2-22)
# Imports: assertthat, utils, stats, plyr, rmeta, Rcpp (>= 0.12.11), mvtnorm, abind, softImpute
# LinkingTo: Rcpp, RcppArmadillo, RcppGSL (>= 0.3.8)
# Suggests: MASS, REBayes, corrplot, testthat, kableExtra, knitr, rmarkdown, profmem, flashr (>= 0.6.7)
# Additional_repositories: https://stephenslab.github.io/flashr-drat
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Biarch: true
# RoxygenNote: 7.1.1
# Packaged: 2021-05-19 13:31:53 UTC; pcarbo
# Author: Matthew Stephens [aut], Sarah Urbut [aut], Gao Wang [aut], Yuxin Zou [aut], Yunqi Yang [ctb], Sam Roweis [cph], David Hogg [cph], Jo Bovy [cph], Peter Carbonetto [aut, cre]
# Maintainer: Peter Carbonetto <peter.carbonetto@gmail.com>
# Repository: CRAN
# Date/Publication: 2021-05-24 00:10:02 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
