{% set package = "ucsc-liftover" %}
{% set program = "liftOver" %}
{% set version = "437" %}

package:
  name: "{{ package }}"
  version: "{{ version }}"

source:
  url: "http://hgdownload.cse.ucsc.edu/admin/exe/userApps.archive/userApps.v{{ version }}.src.tgz"
  patches:
    - "include.patch"

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - libpng
    - libuuid
    - mysql-connector-c
    - libopenssl-static
    - zlib

  run:
    - libpng
    - libuuid
    - mysql-connector-c
    - libopenssl-static
    - zlib

test:
  commands:
    # just check for existence, because the individual packages have no unified behavior
    - which {{ program }}

about:
  home: "http://hgdownload.cse.ucsc.edu/admin/exe/"
  license: "varies; see http://genome.ucsc.edu/license"
  summary: "Move annotations from one assembly to another"
