package:
  name: scmodes
  version: '0.9'

build:
  number: 0

source:
  git_url: /project2/mstephens/aksarkar/projects/scmodes
  git_tag: v0.9

requirements:
  build:
    - numpy >=1.18
    - pandas
    - python >=3.6.9
    - rpy2
    - scikit-learn
    - scipy
    - setuptools
    - pytorch
    - future

  run:
    - numpy >=1.18
    - pandas
    - python >=3.6.9
    - rpy2
    - scikit-learn
    - scipy
    - pytorch
    - future

about:
  home: https://www.github.com/aksarkar/scmodes
  license: MIT
  summary:
    'This package collects implementations of single cell expression models,
    and code to evaluate their performance as described in Sarkar, AK and
    Stephens, M. "Separating measurement and expression models clarifies
    confusion in single-cell RNA sequencing analysis"'
