{% set version = '0.0.0.9000' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-descend
  version: {{ version|replace("-", "_") }}

source:

  git_url: https://github.com/jingshuw/descend
  git_tag: 478f373ec9cf057a6f64614810c554467150aaf6

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}filesystem        # [win]
    - {{posix}}git
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-doparallel
    - r-foreach
    - r-iterators
    - r-quantreg

  run:
    - r-base
    - r-doparallel
    - r-foreach
    - r-iterators
    - r-quantreg

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('descend')"           # [not win]
    - "\"%R%\" -e \"library('descend')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/jingshuw/descend
  license: GPL (>= 2)
  summary: DESCEND deconvolves the true gene expression distribution across cells for UMI scRNA-seq
    counts. It provides estimates of several distribution based statistics (five distribution
    measurements and the coefficients of covariates (such as batches or cell size)).
    Based on the estimation, DESCEND also can perform highly variable selection and
    differential testing of dispersion and burstiness measurements between two groups
    of cells with covariates adjustment.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

# The original CRAN metadata for this package was:

# Package: descend
# Title: Gene Expression Distribution Deconvolution for Single Cell RNA-seq
# Version: 0.0.0.9000
# Authors@R: person("Jingshu", "Wang", email = "jingshuw@upenn.edu", role = c("aut", "cre"))
# Description: DESCEND deconvolves the true gene expression distribution across cells for UMI scRNA-seq counts. It provides estimates of several distribution based statistics (five distribution measurements and the coefficients of covariates (such as batches or cell size)). Based on the estimation, DESCEND also can perform highly variable selection and differential testing of dispersion and burstiness measurements between two groups of cells with covariates adjustment.
# Depends: R (>= 3.3.0)
# Imports: doParallel, methods, quantreg, splines, stats, foreach, iterators
# License: GPL (>= 2)
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.0.1

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
