{% set version = '0.0.3.0436.dev1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mvsusier
  version: {{ version|replace("-", "_") }}

source:

  git_url: https://github.com/stephenslab/mvsusieR
  git_tag: master

build:
  merge_build_host: True  # [win]
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: reshape, cowplot, testthat, microbenchmark, knitr, rmarkdown
requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]

  host:
    - r-abind
    - r-ashr
    - r-base >=3.5.0
    - r-expm
    - r-ggplot2
    - r-grove
    - r-mashr >=0.2.43
    - r-matrix
    - r-matrixstats
    - r-mvtnorm
    - r-progress
    - r-r6
    - r-susier >=0.10.1

  run:
    - r-abind
    - r-ashr
    - r-base >=3.5.0
    - r-expm
    - r-ggplot2
    - r-grove
    - r-mashr >=0.2.43
    - r-matrix
    - r-matrixstats
    - r-mvtnorm
    - r-progress
    - r-r6
    - r-susier >=0.10.1

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('mvsusieR')"           # [not win]
    - "\"%R%\" -e \"library('mvsusieR')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/stephenslab/mvsusieR

  license: MIT
  summary: A more general implementation of the Sum of SIngle Effects (SuSiE) regression for
    Bayesian variable selection.

  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

# The original CRAN metadata for this package was:

# Encoding: UTF-8
# Type: Package
# Package: mvsusieR
# Title: Multivariate Bayesian Variable Selection Regression
# Description: A more general implementation of the Sum of SIngle Effects (SuSiE) regression for Bayesian variable selection.
# Date: 2021-04-08
# Version: 0.0.3.0436
# Authors@R: c(person("Gao","Wang",role=c("aut","cre"), email="wang.gao@columbia.edu"), person("Yuxin","Zou",role="aut"), person("Peter","Carbonetto",role="aut"), person("Matthew","Stephens",role="aut"))
# URL: https://github.com/stephenslab/mvsusieR
# BugReports: https://github.com/stephenslab/mvsusieR/issues
# License: MIT + file LICENSE
# LazyData: true
# NeedsCompilation: no
# RoxygenNote: 7.1.1
# Depends: R (>= 3.5.0), mashr (>= 0.2.43), susieR (>= 0.10.1)
# Imports: R6, methods, graphics, grDevices, stats, Matrix, abind, mvtnorm, matrixStats, expm, progress, grove, ashr, ggplot2
# Suggests: reshape, cowplot, testthat, microbenchmark, knitr, rmarkdown
# Remotes: stephenslab/mashr, stephenslab/susieR
# VignetteBuilder: knitr

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
