{% set version = '0.0.0.9000' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-glmpca
  version: {{ version|replace("-", "_") }}

source:

  git_url: https://github.com/aksarkar/glmpca
  git_tag: 5a0f2ee19fdfa3794a56933d9d05931ac5cb09ac

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}filesystem        # [win]
    - {{posix}}git
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('glmpca')"           # [not win]
    - "\"%R%\" -e \"library('glmpca')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/aksarkar/glmpca
  license: What license is it under?
  summary: What the package does (one paragraph).
  license_family: OTHER

# The original CRAN metadata for this package was:

# Package: glmpca
# Title: What the Package Does (one line, title case)
# Version: 0.0.0.9000
# Authors@R: person("First", "Last", email = "first.last@example.com", role = c("aut", "cre"))
# Description: What the package does (one paragraph).
# Depends: R (>= 3.5.1)
# License: What license is it under?
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.0

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
