{% set version = '0.0.0.9019' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-seuratdisk
  version: {{ version|replace("-", "_") }}

source:

  git_url: https://github.com/mojaveazure/seurat-disk
  git_tag: 163f1aade5bac38ed1e9e9c912283a7e74781610

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: httr, knitr, rmarkdown, SeuratData
requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-matrix >=1.2.18
    - r-r6 >=2.4.1
    - r-seurat >=3.2.0
    - r-seuratobject >=4.0.0
    - r-cli >=2.0.1
    - r-crayon >=1.3.4
    - r-hdf5r >=1.3.0
    - r-rlang >=0.4.4
    - r-stringi >=1.4.6
    - r-withr >=2.1.2

  run:
    - r-base
    - r-matrix >=1.2.18
    - r-r6 >=2.4.1
    - r-seurat >=3.2.0
    - r-seuratobject >=4.0.0
    - r-cli >=2.0.1
    - r-crayon >=1.3.4
    - r-hdf5r >=1.3.0
    - r-rlang >=0.4.4
    - r-stringi >=1.4.6
    - r-withr >=2.1.2

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('SeuratDisk')"           # [not win]
    - "\"%R%\" -e \"library('SeuratDisk')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://mojaveazure.github.io/seurat-disk/, https://github.com/mojaveazure/seurat-disk

  license: GPL-3
  summary: The h5Seurat file format is specifically designed for the storage and analysis of
    multi-modal single-cell and spatially-resolved expression experiments, for example,
    from CITE-seq or 10X Visium technologies. It holds all molecular information and
    associated metadata, including (for example) nearest-neighbor graphs, dimensional
    reduction information, spatial coordinates and image data, and cluster labels. We
    also support rapid and on-disk conversion between h5Seurat and AnnData objects,
    with the goal of enhancing interoperability between Seurat and Scanpy.

  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
    - LICENSE

# The original CRAN metadata for this package was:

# Package: SeuratDisk
# Type: Package
# Title: Interfaces for HDF5-Based Single Cell File Formats
# Version: 0.0.0.9019
# Date: 2021-03-04
# Authors@R: c( person(given = 'Paul', family = 'Hoffman', email = 'phoffman@nygenome.org', role = c('aut', 'cre'), comment = c(ORCID = '0000-0002-7693-8957')), person(given = 'Rahul', family = 'Satija', email = 'rsatija@nygenome.org', role = 'ctb', comment = c(ORCID = '0000-0001-9448-8833')) )
# Description: The h5Seurat file format is specifically designed for the storage and analysis of multi-modal single-cell and spatially-resolved expression experiments, for example, from CITE-seq or 10X Visium technologies. It holds all molecular information and associated metadata, including (for example) nearest-neighbor graphs, dimensional reduction information, spatial coordinates and image data, and cluster labels. We also support rapid and on-disk conversion between h5Seurat and AnnData objects, with the goal of enhancing interoperability between Seurat and Scanpy.
# URL: https://mojaveazure.github.io/seurat-disk/, https://github.com/mojaveazure/seurat-disk
# BugReports: https://github.com/mojaveazure/seurat-disk/issues
# License: GPL-3 | file LICENSE
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.1.1
# Remotes: satijalab/seurat-data
# Depends: R (>= 3.6.0)
# Imports: cli (>= 2.0.1), crayon (>= 1.3.4), hdf5r (>= 1.3.0), Matrix (>= 1.2.18), methods (>= 3.6.0), R6 (>= 2.4.1), rlang (>= 0.4.4), Seurat (>= 3.2.0), SeuratObject (>= 4.0.0), stats, stringi (>= 1.4.6), tools, utils, withr (>= 2.1.2)
# Collate: 'zzz.R' 'GetObject.R' 'AssembleObject.R' 'AppendData.R' 'TestObject.R' 'TestH5.R' 'h5info.R' 'scdisk.R' 'h5Seurat.R' 'Connect.R' 'PadMatrix.R' 'sparse_matrix.R' 'Transpose.R' 'Convert.R' 'LoadH5Seurat.R' 'loom.R' 'loom_bindings.R' 'LoadLoom.R' 'ReadH5.R' 'WriteH5Group.R' 'SaveH5Seurat.R' 'SaveLoom.R' 'h5Seurat_bindings.R'
# Suggests: httr, knitr, rmarkdown, SeuratData
# VignetteBuilder: knitr

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
