package:
  name: r-fasttopics
  version: '0.6.117.dev1'

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

source:
  git_url: git@github.com:stephenslab/fastTopics.git
  git_tag: c8b6e764bd363385dd9ef70433dd939b4a662878

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]

  host:
    - r-ashr
    - r-base
    - r-cowplot
    - r-dplyr
    - r-ggplot2
    - r-ggrepel
    - r-htmlwidgets
    - r-irlba
    - r-matrix
    - r-mcmcpack
    - r-mixsqp
    - r-pbapply
    - r-plotly
    - r-progress
    - r-quadprog
    - r-rcpp (>= 1.0.1)
    - r-rcpparmadillo
    - r-rcppparallel (>= 4.4.1)
    - r-rcppprogress
    - r-rtsne
    - r-uwot

  run:
    - r-ashr
    - r-base
    - r-cowplot
    - r-dplyr
    - r-ggplot2
    - r-ggrepel
    - r-htmlwidgets
    - r-irlba
    - r-matrix
    - r-mcmcpack
    - r-mixsqp
    - r-pbapply
    - r-plotly
    - r-progress
    - r-quadprog
    - r-rcpp (>= 1.0.1)
    - r-rcpparmadillo
    - r-rcppparallel (>= 4.4.1)
    - r-rcppprogress
    - r-rtsne
    - r-uwot
    
test:
  commands:
    - $R -e "library('fastTopics')"           # [not win]
    - "\"%R%\" -e \"library('fastTopics')\""  # [win]

about:
  home: http://github.com/stephenslab/fastTopics
  license: MIT
  summary: 'Fast algorithms for fitting topic models and non-negative
  factorizations to count data.'
  license_family: MIT
  license_file: LICENSE
  description: 'Implements fast, scalable optimization algorithms for fitting
    topic models ("grade of membership" models) and non-negative matrix
    factorizations to count data. The methods exploit the special relationship
    between the multinomial topic model (also, "probabilistic latent semantic
    indexing") and Poisson non-negative matrix factorization. The package
    provides tools to compare, annotate and visualize model fits, including
    functions to efficiently create "structure plots" and identify key features
    in topics. The fastTopics package is a successor to the CountClust
    package.'
