{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mrash
  version: 0.1.dev1

source:
  git_url: https://github.com/stephenslab/mr.ash.alpha
  git_tag: master

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-matrix
    - r-rcpp >=1.0.1
    - r-rcpparmadillo

  run:
    - r-base
    - r-matrix
    - r-rcpp >=1.0.1
    - {{native}}gcc-libs         # [win]
